---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian12-backup
    image: geerlingguy/docker-debian12-ansible@sha256:0b96d8780359f0833bf2d81b5b26ede106beae09c7f22b19a7abeef54770551f
    pre_build_image: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: false
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
      - apparmor=unconfined
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
  env:
    ANSIBLE_BECOME_PROMPT_FLAG: ""
    ANSIBLE_REMOTE_TMP: /tmp/.ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
